baseurl:  /bagpipe
themeurl: /bagpipe/theme
logourl:  /bagpipe/assets/logo.png
iconurl:  /bagpipe/icon.png
repositoryurl: https://github.com/uwplse/bagpipe

layouts: ./theme/_layouts
markdown: kramdown
highlighter: pygments
